services:
  angular-cli:
    build: 
      context: ../../builds/angular
    working_dir: /app
    command: bash
    volumes:
      - ../../src:/app

  angular-cli-legacy:
    build: 
      context: ../../builds/angular-legacy
    working_dir: /app
    command: bash
    volumes:
      - ../../src:/app

  nestjs-cli:
    build: 
      context: ../../builds/nestjs
    working_dir: /app
    command: bash
    volumes:
      - ../../src:/app

  git:
    build: 
      context: ../../builds/git
    working_dir: /app
    command: bash
    volumes:
      - ../../src:/app
    env_file: ../../.env/.local/.git

  mysql:
    build: 
      context: ../../builds/mysql
    volumes:
      - ../../fixtures:/dumps